# Generated by Django 2.1.1 on 2020-05-02 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_auto_20200502_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='members',
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
